# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

variables:
- template: pipeline_templates/vars-global.yml

stages: 
- stage: 'build'
  displayName: 'Build'
  jobs: 
  - job: 'build'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
      displayName: 'npm install'

    - script: |
        npm run build
      displayName: 'npm build'

    - script: |
        npm test
      displayName: 'npm test'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip  

- stage: deploy_test
  variables: 
    - template: pipeline_templates/variables_test.yml
  jobs:
    - deployment: deploymentJob
      pool: 
        vmImage: ${{ variables.vmImageName }}
      environment: ${{ variables.environment }}
      strategy:
        runOnce:
          deploy:
            steps:
              - template: pipeline_templates/deploy-app.yml
                parameters:
                  environment: test
                  webAppName: ${{ variables.webAppName }}
                  appType: ${{ variables.appType }}