
variables:
- template: pipeline_templates/vars-global.yml

stages: 
- stage: 'build'
  displayName: 'Build'
  jobs: 
  - job: 'build'
    steps:
      - template: pipeline_templates/build-app.yml
     

- stage: deploy_test
  variables: 
    - template: pipeline_templates/vars-test.yml
  jobs:
    - deployment: deploymentJob
      pool: 
        vmImage: ${{ variables.vmImageName }}
      environment: ${{ variables.environment }}
      strategy:
        runOnce:
          deploy:
            steps:
              - template: pipeline_templates/deploy-app.yml
                parameters:
                  environment: test
                  webAppName: ${{ variables.webAppName }}
                  appType: ${{ variables.appType }}
                  serviceConnection: ${{ variables.serviceConnection }}

- stage: deploy_dev
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/dev')
  dependsOn: deploy_test
  variables: 
    - template: pipeline_templates/vars-dev.yml
  jobs:
    - deployment: deploymentJob
      pool: 
        vmImage: ${{ variables.vmImageName }}
      environment: ${{ variables.environment }}
      strategy:
        runOnce:
          deploy:
            steps:
              - template: pipeline_templates/deploy-app.yml
                parameters:
                  environment: dev
                  webAppName: ${{ variables.webAppName }}
                  appType: ${{ variables.appType }}
                  serviceConnection: ${{ variables.serviceConnection }}

- stage: deploy_prd
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  dependsOn: deploy_test
  variables: 
    - template: pipeline_templates/vars-prd.yml
  jobs:
    - deployment: deploymentJob
      pool: 
        vmImage: ${{ variables.vmImageName }}
      environment: ${{ variables.environment }}
      strategy:
        runOnce:
          deploy:
            steps:
              - template: pipeline_templates/deploy-app.yml
                parameters:
                  environment: prd
                  webAppName: ${{ variables.webAppName }}
                  appType: ${{ variables.appType }}
                  serviceConnection: ${{ variables.serviceConnection }}