# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

parameters:
  - name: appName
    type: string
    default: kjtech

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    curl https://${{ parameters.appName }}.azurewebsites.net
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- pwsh: |
    try {
        $res=Invoke-WebRequest -Uri 'https://kjtech.azurewebsites.net/'
        $res.StatusCode | Should -Be '200'
        $res
    }
    catch {
        Write-Error $_.Exception.Message
        Exit 1
    }


