stages:
- stage: test
  displayName: Deploy To Test
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: test
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: '
            inputs:
              azureSubscription: 'Pay-As-You-Go (fa8e018e-3a36-4104-ade8-7d8b267fe5b3)'
              appType: 'webAppLinux'
              appName: 'kjtech'
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              runtimeStack: 'NODE|10.10'
              startUpCommand: 'npm run start'