parameters:
- name: environment
  type: string
  default: test
- name: webAppName
  default: kjtech
- name: appType
  default: webAppLinux
- name: resourceGroupName
  default: it-test-use1-jsapp

stages:
- stage: ${{ parameters.environment }}
  displayName: Deploy To ${{ parameters.environment }}
  jobs:
  - job:
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'
  - deployment: Deploy
    displayName: Deploy
    environment: ${{ parameters.environment }}
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy'
            inputs:
              azureSubscription: 'Pay-As-You-Go (fa8e018e-3a36-4104-ade8-7d8b267fe5b3)'
              appType: '${{ parameters.appType }}'
              appName: '${{ parameters.webAppName }}'
              package: '$(System.ArtifactsDirectory)/drop/.zip'
              runtimeStack: 'NODE|10.10'
              startUpCommand: 'npm run start'